name: Backend CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          # FIX: Add the nested folder path here
          cache-dependency-path: lawyer-management-system/backend/package-lock.json

      - name: Install Dependencies
        run: npm ci
        # FIX: Add the nested folder path here
        working-directory: ./lawyer-management-system/backend

      - name: Run Linter
        run: npm run lint
        # FIX: Add the nested folder path here
        working-directory: ./lawyer-management-system/backend

      - name: Run Tests
        run: npm test
        # FIX: Add the nested folder path here
        working-directory: ./lawyer-management-system/backend
        env:
          JWT_SECRET: "a_secret_for_ci_is_fine"
          
      - name: Build Project
        run: npm run build
        # FIX: Add the nested folder path here
        working-directory: ./lawyer-management-system/backend