name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Add this verification step
    - name: Verify backend files
      run: |
        echo "Current directory: $(pwd)"
        ls -la backend/
        [ -f backend/package.json ] && echo "package.json found" || echo "package.json missing"
        
    # Fixed install step
    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend  # Critical fix